apiVersion: apps/v1
kind: Deployment
metadata:
  name: super-mid-deploy
  namespace: staging
spec:
  selector:
    matchLabels:
      app: super-mid
  replicas: 1
  template:
    metadata:
      labels:
        app: super-mid
    spec:
      nodeSelector:
        workfor: biz
      containers:
        - name: super-mid
          image: harbor_url_prod_openmmlab/public/super-mid:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 1
              memory: 3000Mi
          env:
            - name: SUPERMID_ENV
              value: "k8s"
            - name: SUPERMIDEnvMrMeeseeksUrl
              valueFrom:
                secretKeyRef:
                  name: mr-meeseeks-super-mid
                  key: SUPERMIDEnvMrMeeseeksUrl
            - name: SUPERMIDEnvJenkinsUrl
              valueFrom:
                secretKeyRef:
                  name: mr-meeseeks-super-mid
                  key: SUPERMIDEnvJenkinsUrl
            - name: SUPERMIDEnvJenkinsUsername
              valueFrom:
                secretKeyRef:
                  name: mr-meeseeks-super-mid
                  key: SUPERMIDEnvJenkinsUsername
            - name: SUPERMIDEnvJenkinsPassword
              valueFrom:
                secretKeyRef:
                  name: mr-meeseeks-super-mid
                  key: SUPERMIDEnvJenkinsPassword
            - name: SUPERMIDEnvMongoConfigUrl
              valueFrom:
                secretKeyRef:
                  name: mr-meeseeks-super-mid
                  key: SUPERMIDEnvMongoConfigUrl
            - name: SUPERMIDEnvMongoConfigPort
              valueFrom:
                secretKeyRef:
                  name: mr-meeseeks-super-mid
                  key: SUPERMIDEnvMongoConfigPort
            - name: SUPERMIDEnvMongoConfigDatabase
              valueFrom:
                secretKeyRef:
                  name: mr-meeseeks-super-mid
                  key: SUPERMIDEnvMongoConfigDatabase
      imagePullSecrets:
        - name: harbor-registry-key
      securityContext:
        runAsUser: 0
---
apiVersion: v1
kind: Service
metadata:
  name: super-mid-svc
  namespace: staging
spec:
  type: ClusterIP
  selector:
    app: super-mid
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
#apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: super-mid-ingress
  namespace: staging
spec:
  rules:
    - host: super-mid.staging.openxlab.org.cn
      http:
        paths:
          - backend:
              service:
                name: super-mid-service
                port:
                  number: 8080
            path: /
            pathType: Prefix
